FROM ollama/ollama:latest

# Copy custom Modelfile and script to the container
COPY modelsfile/Modelfile /Modelfile
COPY download_models.sh /usr/local/bin/download_models.sh
RUN chmod +x /usr/local/bin/download_models.sh

# Run Ollama server in background, build custom model, run script
ENTRYPOINT ["/bin/sh", "-c", "ollama serve & sleep 2 && ollama create mistral-custom -f /Modelfile && /usr/local/bin/download_models.sh && wait"]
